# Generated by Django 4.2.6 on 2024-09-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostb_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.BigIntegerField(),
        ),
    ]
